images:
  backend:
    tag: "83abbbd"

  frontend:
    tag: "83abbbd"

replicaCount:
  backend: 1
  frontend: 1

frontend:
  service:
    type: NodePort
    port: 80
    nodePort: 30080

postgres:
  storage:
    size: 5Gi

ingress:
  enabled: false
