images:
  backend:
    tag: "49077dc"

  frontend:
    tag: "49077dc"

replicaCount:
  backend: 2
  frontend: 2

frontend:
  service:
    type: NodePort
    port: 80
    nodePort: 30080

postgres:
  storage:
    size: 5Gi

ingress:
  enabled: false
