images:
  backend:
    tag: "b02b1a9"

  frontend:
    tag: "b02b1a9"

replicaCount:
  backend: 2
  frontend: 2

frontend:
  service:
    type: NodePort
    port: 80
    nodePort: 30080

postgres:
  storage:
    size: 5Gi

ingress:
  enabled: false
