apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio.fullname" . }}-secret
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  database-url: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "portfolio.fullname" . }}-postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database }}"
  jwt-secret: "dev-jwt-secret-change-me"
  jwt-refresh-secret: "dev-jwt-refresh-secret-change-me"